version: '3.9'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    volumes:
      - ./volumes/database/postgres-dev:/var/lib/postgresql
    environment:
      POSTGRES_USER: "hudson"
      POSTGRES_PASSWORD: "hudson123"
      POSTGRES_DB: "teste_sicredi"
      TZ: "America/Sao_Paulo"
    ports:
      - "5434:5432"