version: '3.9'

services:
  postgres-db:
    container_name: postgres-db
    image: postgres
    volumes:
      - ./volumes/database/postgres-dev:/var/lib/postgresql
    environment:
      POSTGRES_USER: "hudson"
      POSTGRES_PASSWORD: "hudson123"
      POSTGRES_DB: "teste_sicredi"
      TZ: "America/Sao_Paulo"
    ports:
      - "5434:5432"
    networks:
      - "teste_sicredi"

  teste_sicredi:
    container_name: teste_sicredi
    image: otaldohud/teste_sicredi:1.1.1
    depends_on:
      - postgres-db
    environment:
      URL_DB: "jdbc:postgresql://postgres-db:5432/teste_sicredi"
      TZ: "America/Sao_Paulo"
    ports:
      - "8080:8080"
    networks:
      - "teste_sicredi"


networks:
  teste_sicredi:
    driver: bridge