spring:
  config:
    import:
      - optional:classpath:./variable.properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
  datasource:
    password: ${PASSWORD_DB}
    username: ${USER_DB}
    url: ${URL_DB}
  flyway:
    locations: sql

#PARA TROCAR A PORTA
server:
  port: 8080

